scss_files:
  - 'app/assets/stylesheets/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'vendor/assets/**'
linters:
  ImportantRule:
    enabled: false
  MergeableSelector:
    enabled: false
  UrlFormat:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
  IdSelector:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
